# Alternative simplified spec file for direct kernel module building
# This approach doesn't use the kernel_module_package macro but builds KMP manually

Name:           tuxedo-yt6801-kmp-default
Version:        1.0.30tux2
Release:        1
Summary:        Kernel module for Motorcomm YT6801 ethernet controller
License:        GPL-2.0+
Group:          System/Kernel
URL:            https://www.tuxedocomputers.com
Source0:        tuxedo-yt6801-%{version}.tar.xz
BuildRequires:  kernel-default-devel
BuildRequires:  kernel-syms
Requires:       kernel-default
Provides:       tuxedo-yt6801-kmp = %{version}
Supplements:    modalias(pci:v00001F0Ad00006801sv*sd*bc*sc*i*)
ExclusiveArch:  x86_64
BuildRoot:      %{_tmppath}/%{name}-%{version}-build

%description
This package contains the kernel module for the Motorcomm YT6801 gigabit
ethernet controller. The driver provides support for YT6801-based network
adapters found in various TUXEDO laptops and other systems.

This module is built for the default kernel flavor.

%prep
%setup -q -n tuxedo-yt6801-%{version}

%build
# Build the kernel module
make -C /lib/modules/6.15.8-1-default/build M=$PWD/usr/src/tuxedo-yt6801-%{version} modules

%install
# Install the kernel module
export INSTALL_MOD_PATH=%{buildroot}
export INSTALL_MOD_DIR=updates
mkdir -p %{buildroot}/lib/modules/6.15.8-1-default/updates
cp usr/src/tuxedo-yt6801-%{version}/yt6801.ko %{buildroot}/lib/modules/6.15.8-1-default/updates/

# Install module info
mkdir -p %{buildroot}%{_sysconfdir}/modprobe.d
echo "# Automatically generated by tuxedo-yt6801 package" > %{buildroot}%{_sysconfdir}/modprobe.d/50-tuxedo-yt6801.conf

%files
/lib/modules/6.15.8-1-default/updates/yt6801.ko
%{_sysconfdir}/modprobe.d/50-tuxedo-yt6801.conf

%post
/sbin/depmod -a 6.15.8-1-default || :
# Try to load the module if the hardware is present
if /usr/bin/lspci -d 1f0a:6801 > /dev/null 2>&1; then
    /sbin/modprobe yt6801 > /dev/null 2>&1 || :
fi

%postun
/sbin/depmod -a 6.15.8-1-default || :
# Remove the module if it's loaded
/sbin/rmmod yt6801 > /dev/null 2>&1 || :

%changelog

%changelog
* Wed Jul 16 2025 Tuxedo BOT <tux@tuxedocomputers.com 1.0.30tux2-1
- Dynamically switch power mode on some devices for lower sleep power draw
* Thu Jun 12 2025 Tuxedo BOT <tux@tuxedocomputers.com 1.0.30tux1-1
- Update source to 1.0.30 from upstream
- Update Makefile
- Fix compile error with linux kernel >= v6.15
* Tue Mar 25 2025 Werner Sembach <tux@tuxedocomputers.com 1.0.29tux1-1
- Fix wrong name in Makefile
- Fix compile error because of bogus debug print define
* Wed Aug 28 2024 Werner Sembach <tux@tuxedocomputers.com 1.0.29tux0-1
- Update codebase to 1.0.29
- Convert to native package
* Tue Aug 13 2024 Werner Sembach <tux@tuxedocomputers.com 1.0.28-6-1
- Fix install error
* Tue Aug 13 2024 Werner Sembach <tux@tuxedocomputers.com 1.0.28-5-1
- Don't print warning for normal behaviour
- Fix rpm
* Tue Aug 13 2024 Maximilian Arnold <tux@tuxedocomputers.com 1.0.28-4-1
- Removed reload of the module for chroot environments
* Mon Aug 12 2024 Werner Sembach <tux@tuxedocomputers.com 1.0.28-3-1
- Switch build process to Kbuild instead of Makefile
* Wed Jul 31 2024 Christoffer Sandberg <tux@tuxedocomputers.com 1.0.28-2-1
- Build fix for kernel version
* Wed Apr 03 2024 Werner Sembach <tux@tuxedocomputers.com 1.0.28-1-1
- Initial release.
